var g=TycoonGameManager.Instance;var p=g.player;
var tool=g.looseItems.Single(i=>i.item.kind==TycoonItem.Kind.ImprovedScooper);
if(!tool.Collect(p))throw new System.Exception("Cannot pick up purchased scooper");
p.Select(p.inventory.Locate(TycoonItem.Kind.ImprovedScooper));
var tub=g.Parts(0,TycoonPart.Kind.Tub).First();int stock=tub.contents.amount;
p.target=tub;p.Use(false);
for(int frame=0;frame<120&&p.Held.loadedFlavor<0;frame++)p.Gesture(new UnityEngine.Vector2(0,frame/12%2==0?15:-15),1f/60);
if(p.Held.loadedFlavor!=tub.variant||tub.contents.amount!=stock-1)throw new System.Exception("Improved up/down scoop failed");
string result="Improved scooper: alternating up/down mouse input completed one scoop; stock "+stock+" -> "+tub.contents.amount+".";
System.IO.File.AppendAllText("Library/CodexPlaytests/TycoonOpening.txt","\n"+result);
return result;
